# Workflow to run Basic Test
name: Basic Test Workflow

on:
  workflow_dispatch:

jobs:
  run-basic-test:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:

      # Set screen resolution
      - name: 'Screen resolution 1920x1080'
        run: 'Set-DisplayResolution -Width 1920 -Height 1080 -Force'

      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Run Katalon test
      - name: Run Basic Test
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '10.4.2'
          projectPath: ${{ github.workspace }}
          args: 'katalonc -noSplash -retry=0 -testSuitePath="Test Suites/New Test Suite"'
